import Head from 'next/head'
export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Eldoret Realtors</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main data-theme="emerald" className="container mx-auto px-6 mt-2">
                {children}
            </main>
        </>
    )
}
